#!/bin/bash
# makes directory on all ec2 instances

source ec2-config

# if not enough arguments print usage
if [ "$#" -lt 1 ]; then
    echo "Usage:  $(basename $0) instance_new_directory"
    echo "  example: $(basename $0) /new/directory/on/instances "
    exit
fi
echo "Making directory $1"
pssh -P -h public_ip.txt -l "ubuntu"  'source ~/.profile; mkdir' $1

exit


# store public ips in an array
iparr=($(cat public_ip.txt | awk '{ print $1 }'))

for i in "${iparr[@]}"
do
	ssh  -q -i ${SWIFT_EC2_KEY}  $SWIFT_EC2_USER@${i} 'source ~/.profile; mkdir' $1 &
done

wait