#!/bin/bash
# processes and combines results

rm ${1}/${2}-mbs 2> /dev/null
rm ${1}/${2}-mbs-normalized 2> /dev/null
rm ${1}/${2}-records 2> /dev/null

cat ${1}/*/${2}-records > ${1}/${2}-records
cat ${1}/${2}-records | awk '{ print 1024/$3 }' > ${1}/${2}-mbs-normalized
echo
echo "$2 records :"
echo "$(cat ${1}/${2}-records | wc -l ) $2 records downloaded:"
#cat  ${1}/${2}-records
