#!/bin/bash

# Mount FusionFS

source ec2-config

# if arguments are give  print usage
if [ "$#" -gt 0 ]; then
echo "Usage:  $(basename $0) "
exit
fi
echo "Starting FusionFS"
pssh -P -h public_ip.txt -l "ubuntu"  "source ~/.profile; cd $(dirname $FUSIONFS_EC2_START);$FUSIONFS_EC2_START >> /dev/null "
exit



# store public ips in an array
iparr=($(cat public_ip.txt | awk '{ print $1 }'))

for j in "${iparr[@]}"
do
    echo "starting fusionfs on node $j"
ssh -i ${FUSIONFS_EC2_KEY} $FUSIONFS_EC2_USER@${j} "source ~/.profile; cd $(dirname $FUSIONFS_EC2_START);$FUSIONFS_EC2_START"   #start fusionfs
    echo
done
#wait

#pssh -P -h public_ip.txt -l "ubuntu"  "source ~/.profile; cd $(dirname $FUSIONFS_EC2_START);$FUSIONFS_EC2_START >> /dev/null "

# wait